<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CountryTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('country')->truncate();
        $Countries = array(
            array('country_id' => 1, 'counrty_code' => 'AF', 'country_name' => "Afghanistan", 'phone_code' => 93),
            array('country_id' => 2, 'counrty_code' => 'AL', 'country_name' => "Albania", 'phone_code' => 355),
            array('country_id' => 3, 'counrty_code' => 'DZ', 'country_name' => "Algeria", 'phone_code' => 213),
            array('country_id' => 4, 'counrty_code' => 'AS', 'country_name' => "American Samoa", 'phone_code' => 1684),
            array('country_id' => 5, 'counrty_code' => 'AD', 'country_name' => "Andorra", 'phone_code' => 376),
            array('country_id' => 6, 'counrty_code' => 'AO', 'country_name' => "Angola", 'phone_code' => 244),
            array('country_id' => 7, 'counrty_code' => 'AI', 'country_name' => "Anguilla", 'phone_code' => 1264),
            array('country_id' => 8, 'counrty_code' => 'AQ', 'country_name' => "Antarctica", 'phone_code' => 0),
            array('country_id' => 9, 'counrty_code' => 'AG', 'country_name' => "Antigua And Barbuda", 'phone_code' => 1268),
            array('country_id' => 10, 'counrty_code' => 'AR', 'country_name' => "Argentina", 'phone_code' => 54),
            array('country_id' => 11, 'counrty_code' => 'AM', 'country_name' => "Armenia", 'phone_code' => 374),
            array('country_id' => 12, 'counrty_code' => 'AW', 'country_name' => "Aruba", 'phone_code' => 297),
            array('country_id' => 13, 'counrty_code' => 'AU', 'country_name' => "Australia", 'phone_code' => 61),
            array('country_id' => 14, 'counrty_code' => 'AT', 'country_name' => "Austria", 'phone_code' => 43),
            array('country_id' => 15, 'counrty_code' => 'AZ', 'country_name' => "Azerbaijan", 'phone_code' => 994),
            array('country_id' => 16, 'counrty_code' => 'BS', 'country_name' => "Bahamas The", 'phone_code' => 1242),
            array('country_id' => 17, 'counrty_code' => 'BH', 'country_name' => "Bahrain", 'phone_code' => 973),
            array('country_id' => 18, 'counrty_code' => 'BD', 'country_name' => "Bangladesh", 'phone_code' => 880),
            array('country_id' => 19, 'counrty_code' => 'BB', 'country_name' => "Barbados", 'phone_code' => 1246),
            array('country_id' => 20, 'counrty_code' => 'BY', 'country_name' => "Belarus", 'phone_code' => 375),
            array('country_id' => 21, 'counrty_code' => 'BE', 'country_name' => "Belgium", 'phone_code' => 32),
            array('country_id' => 22, 'counrty_code' => 'BZ', 'country_name' => "Belize", 'phone_code' => 501),
            array('country_id' => 23, 'counrty_code' => 'BJ', 'country_name' => "Benin", 'phone_code' => 229),
            array('country_id' => 24, 'counrty_code' => 'BM', 'country_name' => "Bermuda", 'phone_code' => 1441),
            array('country_id' => 25, 'counrty_code' => 'BT', 'country_name' => "Bhutan", 'phone_code' => 975),
            array('country_id' => 26, 'counrty_code' => 'BO', 'country_name' => "Bolivia", 'phone_code' => 591),
            array('country_id' => 27, 'counrty_code' => 'BA', 'country_name' => "Bosnia and Herzegovina", 'phone_code' => 387),
            array('country_id' => 28, 'counrty_code' => 'BW', 'country_name' => "Botswana", 'phone_code' => 267),
            array('country_id' => 29, 'counrty_code' => 'BV', 'country_name' => "Bouvet Island", 'phone_code' => 0),
            array('country_id' => 30, 'counrty_code' => 'BR', 'country_name' => "Brazil", 'phone_code' => 55),
            array('country_id' => 31, 'counrty_code' => 'IO', 'country_name' => "British Indian Ocean Territory", 'phone_code' => 246),
            array('country_id' => 32, 'counrty_code' => 'BN', 'country_name' => "Brunei", 'phone_code' => 673),
            array('country_id' => 33, 'counrty_code' => 'BG', 'country_name' => "Bulgaria", 'phone_code' => 359),
            array('country_id' => 34, 'counrty_code' => 'BF', 'country_name' => "Burkina Faso", 'phone_code' => 226),
            array('country_id' => 35, 'counrty_code' => 'BI', 'country_name' => "Burundi", 'phone_code' => 257),
            array('country_id' => 36, 'counrty_code' => 'KH', 'country_name' => "Cambodia", 'phone_code' => 855),
            array('country_id' => 37, 'counrty_code' => 'CM', 'country_name' => "Cameroon", 'phone_code' => 237),
            array('country_id' => 38, 'counrty_code' => 'CA', 'country_name' => "Canada", 'phone_code' => 1),
            array('country_id' => 39, 'counrty_code' => 'CV', 'country_name' => "Cape Verde", 'phone_code' => 238),
            array('country_id' => 40, 'counrty_code' => 'KY', 'country_name' => "Cayman Islands", 'phone_code' => 1345),
            array('country_id' => 41, 'counrty_code' => 'CF', 'country_name' => "Central African Republic", 'phone_code' => 236),
            array('country_id' => 42, 'counrty_code' => 'TD', 'country_name' => "Chad", 'phone_code' => 235),
            array('country_id' => 43, 'counrty_code' => 'CL', 'country_name' => "Chile", 'phone_code' => 56),
            array('country_id' => 44, 'counrty_code' => 'CN', 'country_name' => "China", 'phone_code' => 86),
            array('country_id' => 45, 'counrty_code' => 'CX', 'country_name' => "Christmas Island", 'phone_code' => 61),
            array('country_id' => 46, 'counrty_code' => 'CC', 'country_name' => "Cocos (Keeling) Islands", 'phone_code' => 672),
            array('country_id' => 47, 'counrty_code' => 'CO', 'country_name' => "Colombia", 'phone_code' => 57),
            array('country_id' => 48, 'counrty_code' => 'KM', 'country_name' => "Comoros", 'phone_code' => 269),
            array('country_id' => 49, 'counrty_code' => 'CG', 'country_name' => "Congo", 'phone_code' => 242),
            array('country_id' => 50, 'counrty_code' => 'CD', 'country_name' => "Congo The Democratic Republic Of The", 'phone_code' => 242),
            array('country_id' => 51, 'counrty_code' => 'CK', 'country_name' => "Cook Islands", 'phone_code' => 682),
            array('country_id' => 52, 'counrty_code' => 'CR', 'country_name' => "Costa Rica", 'phone_code' => 506),
            array('country_id' => 53, 'counrty_code' => 'CI', 'country_name' => "Cote D Ivoire (Ivory Coast)", 'phone_code' => 225),
            array('country_id' => 54, 'counrty_code' => 'HR', 'country_name' => "Croatia (Hrvatska)", 'phone_code' => 385),
            array('country_id' => 55, 'counrty_code' => 'CU', 'country_name' => "Cuba", 'phone_code' => 53),
            array('country_id' => 56, 'counrty_code' => 'CY', 'country_name' => "Cyprus", 'phone_code' => 357),
            array('country_id' => 57, 'counrty_code' => 'CZ', 'country_name' => "Czech Republic", 'phone_code' => 420),
            array('country_id' => 58, 'counrty_code' => 'DK', 'country_name' => "Denmark", 'phone_code' => 45),
            array('country_id' => 59, 'counrty_code' => 'DJ', 'country_name' => "Djibouti", 'phone_code' => 253),
            array('country_id' => 60, 'counrty_code' => 'DM', 'country_name' => "Dominica", 'phone_code' => 1767),
            array('country_id' => 61, 'counrty_code' => 'DO', 'country_name' => "Dominican Republic", 'phone_code' => 1809),
            array('country_id' => 62, 'counrty_code' => 'TP', 'country_name' => "East Timor", 'phone_code' => 670),
            array('country_id' => 63, 'counrty_code' => 'EC', 'country_name' => "Ecuador", 'phone_code' => 593),
            array('country_id' => 64, 'counrty_code' => 'EG', 'country_name' => "Egypt", 'phone_code' => 20),
            array('country_id' => 65, 'counrty_code' => 'SV', 'country_name' => "El Salvador", 'phone_code' => 503),
            array('country_id' => 66, 'counrty_code' => 'GQ', 'country_name' => "Equatorial Guinea", 'phone_code' => 240),
            array('country_id' => 67, 'counrty_code' => 'ER', 'country_name' => "Eritrea", 'phone_code' => 291),
            array('country_id' => 68, 'counrty_code' => 'EE', 'country_name' => "Estonia", 'phone_code' => 372),
            array('country_id' => 69, 'counrty_code' => 'ET', 'country_name' => "Ethiopia", 'phone_code' => 251),
            array('country_id' => 70, 'counrty_code' => 'XA', 'country_name' => "External Territories of Australia", 'phone_code' => 61),
            array('country_id' => 71, 'counrty_code' => 'FK', 'country_name' => "Falkland Islands", 'phone_code' => 500),
            array('country_id' => 72, 'counrty_code' => 'FO', 'country_name' => "Faroe Islands", 'phone_code' => 298),
            array('country_id' => 73, 'counrty_code' => 'FJ', 'country_name' => "Fiji Islands", 'phone_code' => 679),
            array('country_id' => 74, 'counrty_code' => 'FI', 'country_name' => "Finland", 'phone_code' => 358),
            array('country_id' => 75, 'counrty_code' => 'FR', 'country_name' => "France", 'phone_code' => 33),
            array('country_id' => 76, 'counrty_code' => 'GF', 'country_name' => "French Guiana", 'phone_code' => 594),
            array('country_id' => 77, 'counrty_code' => 'PF', 'country_name' => "French Polynesia", 'phone_code' => 689),
            array('country_id' => 78, 'counrty_code' => 'TF', 'country_name' => "French Southern Territories", 'phone_code' => 0),
            array('country_id' => 79, 'counrty_code' => 'GA', 'country_name' => "Gabon", 'phone_code' => 241),
            array('country_id' => 80, 'counrty_code' => 'GM', 'country_name' => "Gambia The", 'phone_code' => 220),
            array('country_id' => 81, 'counrty_code' => 'GE', 'country_name' => "Georgia", 'phone_code' => 995),
            array('country_id' => 82, 'counrty_code' => 'DE', 'country_name' => "Germany", 'phone_code' => 49),
            array('country_id' => 83, 'counrty_code' => 'GH', 'country_name' => "Ghana", 'phone_code' => 233),
            array('country_id' => 84, 'counrty_code' => 'GI', 'country_name' => "Gibraltar", 'phone_code' => 350),
            array('country_id' => 85, 'counrty_code' => 'GR', 'country_name' => "Greece", 'phone_code' => 30),
            array('country_id' => 86, 'counrty_code' => 'GL', 'country_name' => "Greenland", 'phone_code' => 299),
            array('country_id' => 87, 'counrty_code' => 'GD', 'country_name' => "Grenada", 'phone_code' => 1473),
            array('country_id' => 88, 'counrty_code' => 'GP', 'country_name' => "Guadeloupe", 'phone_code' => 590),
            array('country_id' => 89, 'counrty_code' => 'GU', 'country_name' => "Guam", 'phone_code' => 1671),
            array('country_id' => 90, 'counrty_code' => 'GT', 'country_name' => "Guatemala", 'phone_code' => 502),
            array('country_id' => 91, 'counrty_code' => 'XU', 'country_name' => "Guernsey and Alderney", 'phone_code' => 44),
            array('country_id' => 92, 'counrty_code' => 'GN', 'country_name' => "Guinea", 'phone_code' => 224),
            array('country_id' => 93, 'counrty_code' => 'GW', 'country_name' => "Guinea-Bissau", 'phone_code' => 245),
            array('country_id' => 94, 'counrty_code' => 'GY', 'country_name' => "Guyana", 'phone_code' => 592),
            array('country_id' => 95, 'counrty_code' => 'HT', 'country_name' => "Haiti", 'phone_code' => 509),
            array('country_id' => 96, 'counrty_code' => 'HM', 'country_name' => "Heard and McDonald Islands", 'phone_code' => 0),
            array('country_id' => 97, 'counrty_code' => 'HN', 'country_name' => "Honduras", 'phone_code' => 504),
            array('country_id' => 98, 'counrty_code' => 'HK', 'country_name' => "Hong Kong S.A.R.", 'phone_code' => 852),
            array('country_id' => 99, 'counrty_code' => 'HU', 'country_name' => "Hungary", 'phone_code' => 36),
            array('country_id' => 100, 'counrty_code' => 'IS', 'country_name' => "Iceland", 'phone_code' => 354),
            array('country_id' => 101, 'counrty_code' => 'IN', 'country_name' => "India", 'phone_code' => 91),
            array('country_id' => 102, 'counrty_code' => 'country_id', 'country_name' => "Indonesia", 'phone_code' => 62),
            array('country_id' => 103, 'counrty_code' => 'IR', 'country_name' => "Iran", 'phone_code' => 98),
            array('country_id' => 104, 'counrty_code' => 'IQ', 'country_name' => "Iraq", 'phone_code' => 964),
            array('country_id' => 105, 'counrty_code' => 'IE', 'country_name' => "Ireland", 'phone_code' => 353),
            array('country_id' => 106, 'counrty_code' => 'IL', 'country_name' => "Israel", 'phone_code' => 972),
            array('country_id' => 107, 'counrty_code' => 'IT', 'country_name' => "Italy", 'phone_code' => 39),
            array('country_id' => 108, 'counrty_code' => 'JM', 'country_name' => "Jamaica", 'phone_code' => 1876),
            array('country_id' => 109, 'counrty_code' => 'JP', 'country_name' => "Japan", 'phone_code' => 81),
            array('country_id' => 110, 'counrty_code' => 'XJ', 'country_name' => "Jersey", 'phone_code' => 44),
            array('country_id' => 111, 'counrty_code' => 'JO', 'country_name' => "Jordan", 'phone_code' => 962),
            array('country_id' => 112, 'counrty_code' => 'KZ', 'country_name' => "Kazakhstan", 'phone_code' => 7),
            array('country_id' => 113, 'counrty_code' => 'KE', 'country_name' => "Kenya", 'phone_code' => 254),
            array('country_id' => 114, 'counrty_code' => 'KI', 'country_name' => "Kiribati", 'phone_code' => 686),
            array('country_id' => 115, 'counrty_code' => 'KP', 'country_name' => "Korea North", 'phone_code' => 850),
            array('country_id' => 116, 'counrty_code' => 'KR', 'country_name' => "Korea South", 'phone_code' => 82),
            array('country_id' => 117, 'counrty_code' => 'KW', 'country_name' => "Kuwait", 'phone_code' => 965),
            array('country_id' => 118, 'counrty_code' => 'KG', 'country_name' => "Kyrgyzstan", 'phone_code' => 996),
            array('country_id' => 119, 'counrty_code' => 'LA', 'country_name' => "Laos", 'phone_code' => 856),
            array('country_id' => 120, 'counrty_code' => 'LV', 'country_name' => "Latvia", 'phone_code' => 371),
            array('country_id' => 121, 'counrty_code' => 'LB', 'country_name' => "Lebanon", 'phone_code' => 961),
            array('country_id' => 122, 'counrty_code' => 'LS', 'country_name' => "Lesotho", 'phone_code' => 266),
            array('country_id' => 123, 'counrty_code' => 'LR', 'country_name' => "Liberia", 'phone_code' => 231),
            array('country_id' => 124, 'counrty_code' => 'LY', 'country_name' => "Libya", 'phone_code' => 218),
            array('country_id' => 125, 'counrty_code' => 'LI', 'country_name' => "Liechtenstein", 'phone_code' => 423),
            array('country_id' => 126, 'counrty_code' => 'LT', 'country_name' => "Lithuania", 'phone_code' => 370),
            array('country_id' => 127, 'counrty_code' => 'LU', 'country_name' => "Luxembourg", 'phone_code' => 352),
            array('country_id' => 128, 'counrty_code' => 'MO', 'country_name' => "Macau S.A.R.", 'phone_code' => 853),
            array('country_id' => 129, 'counrty_code' => 'MK', 'country_name' => "Macedonia", 'phone_code' => 389),
            array('country_id' => 130, 'counrty_code' => 'MG', 'country_name' => "Madagascar", 'phone_code' => 261),
            array('country_id' => 131, 'counrty_code' => 'MW', 'country_name' => "Malawi", 'phone_code' => 265),
            array('country_id' => 132, 'counrty_code' => 'MY', 'country_name' => "Malaysia", 'phone_code' => 60),
            array('country_id' => 133, 'counrty_code' => 'MV', 'country_name' => "Maldives", 'phone_code' => 960),
            array('country_id' => 134, 'counrty_code' => 'ML', 'country_name' => "Mali", 'phone_code' => 223),
            array('country_id' => 135, 'counrty_code' => 'MT', 'country_name' => "Malta", 'phone_code' => 356),
            array('country_id' => 136, 'counrty_code' => 'XM', 'country_name' => "Man (Isle of)", 'phone_code' => 44),
            array('country_id' => 137, 'counrty_code' => 'MH', 'country_name' => "Marshall Islands", 'phone_code' => 692),
            array('country_id' => 138, 'counrty_code' => 'MQ', 'country_name' => "Martinique", 'phone_code' => 596),
            array('country_id' => 139, 'counrty_code' => 'MR', 'country_name' => "Mauritania", 'phone_code' => 222),
            array('country_id' => 140, 'counrty_code' => 'MU', 'country_name' => "Mauritius", 'phone_code' => 230),
            array('country_id' => 141, 'counrty_code' => 'YT', 'country_name' => "Mayotte", 'phone_code' => 269),
            array('country_id' => 142, 'counrty_code' => 'MX', 'country_name' => "Mexico", 'phone_code' => 52),
            array('country_id' => 143, 'counrty_code' => 'FM', 'country_name' => "Micronesia", 'phone_code' => 691),
            array('country_id' => 144, 'counrty_code' => 'MD', 'country_name' => "Moldova", 'phone_code' => 373),
            array('country_id' => 145, 'counrty_code' => 'MC', 'country_name' => "Monaco", 'phone_code' => 377),
            array('country_id' => 146, 'counrty_code' => 'MN', 'country_name' => "Mongolia", 'phone_code' => 976),
            array('country_id' => 147, 'counrty_code' => 'MS', 'country_name' => "Montserrat", 'phone_code' => 1664),
            array('country_id' => 148, 'counrty_code' => 'MA', 'country_name' => "Morocco", 'phone_code' => 212),
            array('country_id' => 149, 'counrty_code' => 'MZ', 'country_name' => "Mozambique", 'phone_code' => 258),
            array('country_id' => 150, 'counrty_code' => 'MM', 'country_name' => "Myanmar", 'phone_code' => 95),
            array('country_id' => 151, 'counrty_code' => 'NA', 'country_name' => "Namibia", 'phone_code' => 264),
            array('country_id' => 152, 'counrty_code' => 'NR', 'country_name' => "Nauru", 'phone_code' => 674),
            array('country_id' => 153, 'counrty_code' => 'NP', 'country_name' => "Nepal", 'phone_code' => 977),
            array('country_id' => 154, 'counrty_code' => 'AN', 'country_name' => "Netherlands Antilles", 'phone_code' => 599),
            array('country_id' => 155, 'counrty_code' => 'NL', 'country_name' => "Netherlands The", 'phone_code' => 31),
            array('country_id' => 156, 'counrty_code' => 'NC', 'country_name' => "New Caledonia", 'phone_code' => 687),
            array('country_id' => 157, 'counrty_code' => 'NZ', 'country_name' => "New Zealand", 'phone_code' => 64),
            array('country_id' => 158, 'counrty_code' => 'NI', 'country_name' => "Nicaragua", 'phone_code' => 505),
            array('country_id' => 159, 'counrty_code' => 'NE', 'country_name' => "Niger", 'phone_code' => 227),
            array('country_id' => 160, 'counrty_code' => 'NG', 'country_name' => "Nigeria", 'phone_code' => 234),
            array('country_id' => 161, 'counrty_code' => 'NU', 'country_name' => "Niue", 'phone_code' => 683),
            array('country_id' => 162, 'counrty_code' => 'NF', 'country_name' => "Norfolk Island", 'phone_code' => 672),
            array('country_id' => 163, 'counrty_code' => 'MP', 'country_name' => "Northern Mariana Islands", 'phone_code' => 1670),
            array('country_id' => 164, 'counrty_code' => 'NO', 'country_name' => "Norway", 'phone_code' => 47),
            array('country_id' => 165, 'counrty_code' => 'OM', 'country_name' => "Oman", 'phone_code' => 968),
            array('country_id' => 166, 'counrty_code' => 'PK', 'country_name' => "Pakistan", 'phone_code' => 92),
            array('country_id' => 167, 'counrty_code' => 'PW', 'country_name' => "Palau", 'phone_code' => 680),
            array('country_id' => 168, 'counrty_code' => 'PS', 'country_name' => "Palestinian Territory Occupied", 'phone_code' => 970),
            array('country_id' => 169, 'counrty_code' => 'PA', 'country_name' => "Panama", 'phone_code' => 507),
            array('country_id' => 170, 'counrty_code' => 'PG', 'country_name' => "Papua new Guinea", 'phone_code' => 675),
            array('country_id' => 171, 'counrty_code' => 'PY', 'country_name' => "Paraguay", 'phone_code' => 595),
            array('country_id' => 172, 'counrty_code' => 'PE', 'country_name' => "Peru", 'phone_code' => 51),
            array('country_id' => 173, 'counrty_code' => 'PH', 'country_name' => "Philippines", 'phone_code' => 63),
            array('country_id' => 174, 'counrty_code' => 'PN', 'country_name' => "Pitcairn Island", 'phone_code' => 0),
            array('country_id' => 175, 'counrty_code' => 'PL', 'country_name' => "Poland", 'phone_code' => 48),
            array('country_id' => 176, 'counrty_code' => 'PT', 'country_name' => "Portugal", 'phone_code' => 351),
            array('country_id' => 177, 'counrty_code' => 'PR', 'country_name' => "Puerto Rico", 'phone_code' => 1787),
            array('country_id' => 178, 'counrty_code' => 'QA', 'country_name' => "Qatar", 'phone_code' => 974),
            array('country_id' => 179, 'counrty_code' => 'RE', 'country_name' => "Reunion", 'phone_code' => 262),
            array('country_id' => 180, 'counrty_code' => 'RO', 'country_name' => "Romania", 'phone_code' => 40),
            array('country_id' => 181, 'counrty_code' => 'RU', 'country_name' => "Russia", 'phone_code' => 70),
            array('country_id' => 182, 'counrty_code' => 'RW', 'country_name' => "Rwanda", 'phone_code' => 250),
            array('country_id' => 183, 'counrty_code' => 'SH', 'country_name' => "Saint Helena", 'phone_code' => 290),
            array('country_id' => 184, 'counrty_code' => 'KN', 'country_name' => "Saint Kitts And Nevis", 'phone_code' => 1869),
            array('country_id' => 185, 'counrty_code' => 'LC', 'country_name' => "Saint Lucia", 'phone_code' => 1758),
            array('country_id' => 186, 'counrty_code' => 'PM', 'country_name' => "Saint Pierre and Miquelon", 'phone_code' => 508),
            array('country_id' => 187, 'counrty_code' => 'VC', 'country_name' => "Saint Vincent And The Grenadines", 'phone_code' => 1784),
            array('country_id' => 188, 'counrty_code' => 'WS', 'country_name' => "Samoa", 'phone_code' => 684),
            array('country_id' => 189, 'counrty_code' => 'SM', 'country_name' => "San Marino", 'phone_code' => 378),
            array('country_id' => 190, 'counrty_code' => 'ST', 'country_name' => "Sao Tome and Principe", 'phone_code' => 239),
            array('country_id' => 191, 'counrty_code' => 'SA', 'country_name' => "Saudi Arabia", 'phone_code' => 966),
            array('country_id' => 192, 'counrty_code' => 'SN', 'country_name' => "Senegal", 'phone_code' => 221),
            array('country_id' => 193, 'counrty_code' => 'RS', 'country_name' => "Serbia", 'phone_code' => 381),
            array('country_id' => 194, 'counrty_code' => 'SC', 'country_name' => "Seychelles", 'phone_code' => 248),
            array('country_id' => 195, 'counrty_code' => 'SL', 'country_name' => "Sierra Leone", 'phone_code' => 232),
            array('country_id' => 196, 'counrty_code' => 'SG', 'country_name' => "Singapore", 'phone_code' => 65),
            array('country_id' => 197, 'counrty_code' => 'SK', 'country_name' => "Slovakia", 'phone_code' => 421),
            array('country_id' => 198, 'counrty_code' => 'SI', 'country_name' => "Slovenia", 'phone_code' => 386),
            array('country_id' => 199, 'counrty_code' => 'XG', 'country_name' => "Smaller Territories of the UK", 'phone_code' => 44),
            array('country_id' => 200, 'counrty_code' => 'SB', 'country_name' => "Solomon Islands", 'phone_code' => 677),
            array('country_id' => 201, 'counrty_code' => 'SO', 'country_name' => "Somalia", 'phone_code' => 252),
            array('country_id' => 202, 'counrty_code' => 'ZA', 'country_name' => "South Africa", 'phone_code' => 27),
            array('country_id' => 203, 'counrty_code' => 'GS', 'country_name' => "South Georgia", 'phone_code' => 0),
            array('country_id' => 204, 'counrty_code' => 'SS', 'country_name' => "South Sudan", 'phone_code' => 211),
            array('country_id' => 205, 'counrty_code' => 'ES', 'country_name' => "Spain", 'phone_code' => 34),
            array('country_id' => 206, 'counrty_code' => 'LK', 'country_name' => "Sri Lanka", 'phone_code' => 94),
            array('country_id' => 207, 'counrty_code' => 'SD', 'country_name' => "Sudan", 'phone_code' => 249),
            array('country_id' => 208, 'counrty_code' => 'SR', 'country_name' => "Suriname", 'phone_code' => 597),
            array('country_id' => 209, 'counrty_code' => 'SJ', 'country_name' => "Svalbard And Jan Mayen Islands", 'phone_code' => 47),
            array('country_id' => 210, 'counrty_code' => 'SZ', 'country_name' => "Swaziland", 'phone_code' => 268),
            array('country_id' => 211, 'counrty_code' => 'SE', 'country_name' => "Sweden", 'phone_code' => 46),
            array('country_id' => 212, 'counrty_code' => 'CH', 'country_name' => "Switzerland", 'phone_code' => 41),
            array('country_id' => 213, 'counrty_code' => 'SY', 'country_name' => "Syria", 'phone_code' => 963),
            array('country_id' => 214, 'counrty_code' => 'TW', 'country_name' => "Taiwan", 'phone_code' => 886),
            array('country_id' => 215, 'counrty_code' => 'TJ', 'country_name' => "Tajikistan", 'phone_code' => 992),
            array('country_id' => 216, 'counrty_code' => 'TZ', 'country_name' => "Tanzania", 'phone_code' => 255),
            array('country_id' => 217, 'counrty_code' => 'TH', 'country_name' => "Thailand", 'phone_code' => 66),
            array('country_id' => 218, 'counrty_code' => 'TG', 'country_name' => "Togo", 'phone_code' => 228),
            array('country_id' => 219, 'counrty_code' => 'TK', 'country_name' => "Tokelau", 'phone_code' => 690),
            array('country_id' => 220, 'counrty_code' => 'TO', 'country_name' => "Tonga", 'phone_code' => 676),
            array('country_id' => 221, 'counrty_code' => 'TT', 'country_name' => "Trinidad And Tobago", 'phone_code' => 1868),
            array('country_id' => 222, 'counrty_code' => 'TN', 'country_name' => "Tunisia", 'phone_code' => 216),
            array('country_id' => 223, 'counrty_code' => 'TR', 'country_name' => "Turkey", 'phone_code' => 90),
            array('country_id' => 224, 'counrty_code' => 'TM', 'country_name' => "Turkmenistan", 'phone_code' => 7370),
            array('country_id' => 225, 'counrty_code' => 'TC', 'country_name' => "Turks And Caicos Islands", 'phone_code' => 1649),
            array('country_id' => 226, 'counrty_code' => 'TV', 'country_name' => "Tuvalu", 'phone_code' => 688),
            array('country_id' => 227, 'counrty_code' => 'UG', 'country_name' => "Uganda", 'phone_code' => 256),
            array('country_id' => 228, 'counrty_code' => 'UA', 'country_name' => "Ukraine", 'phone_code' => 380),
            array('country_id' => 229, 'counrty_code' => 'AE', 'country_name' => "United Arab Emirates", 'phone_code' => 971),
            array('country_id' => 230, 'counrty_code' => 'GB', 'country_name' => "United Kingdom", 'phone_code' => 44),
            array('country_id' => 231, 'counrty_code' => 'US', 'country_name' => "United States", 'phone_code' => 1),
            array('country_id' => 232, 'counrty_code' => 'UM', 'country_name' => "United States Minor Outlying Islands", 'phone_code' => 1),
            array('country_id' => 233, 'counrty_code' => 'UY', 'country_name' => "Uruguay", 'phone_code' => 598),
            array('country_id' => 234, 'counrty_code' => 'UZ', 'country_name' => "Uzbekistan", 'phone_code' => 998),
            array('country_id' => 235, 'counrty_code' => 'VU', 'country_name' => "Vanuatu", 'phone_code' => 678),
            array('country_id' => 236, 'counrty_code' => 'VA', 'country_name' => "Vatican City State (Holy See)", 'phone_code' => 39),
            array('country_id' => 237, 'counrty_code' => 'VE', 'country_name' => "Venezuela", 'phone_code' => 58),
            array('country_id' => 238, 'counrty_code' => 'VN', 'country_name' => "Vietnam", 'phone_code' => 84),
            array('country_id' => 239, 'counrty_code' => 'VG', 'country_name' => "Virgin Islands (British)", 'phone_code' => 1284),
            array('country_id' => 240, 'counrty_code' => 'VI', 'country_name' => "Virgin Islands (US)", 'phone_code' => 1340),
            array('country_id' => 241, 'counrty_code' => 'WF', 'country_name' => "Wallis And Futuna Islands", 'phone_code' => 681),
            array('country_id' => 242, 'counrty_code' => 'EH', 'country_name' => "Western Sahara", 'phone_code' => 212),
            array('country_id' => 243, 'counrty_code' => 'YE', 'country_name' => "Yemen", 'phone_code' => 967),
            array('country_id' => 244, 'counrty_code' => 'YU', 'country_name' => "Yugoslavia", 'phone_code' => 38),
            array('country_id' => 245, 'counrty_code' => 'ZM', 'country_name' => "Zambia", 'phone_code' => 260),
            array('country_id' => 246, 'counrty_code' => 'ZW', 'country_name' => "Zimbabwe", 'phone_code' => 263),
        );
        DB::table('country')->insert($Countries);
    }
}
